#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models.ChamCong
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDChamCong")]
	public partial class LinqChamCongServerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSys_ParameterTemp(Sys_ParameterTemp instance);
    partial void UpdateSys_ParameterTemp(Sys_ParameterTemp instance);
    partial void DeleteSys_ParameterTemp(Sys_ParameterTemp instance);
    #endregion
		
		public LinqChamCongServerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BDChamCongConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqChamCongServerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqChamCongServerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqChamCongServerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqChamCongServerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<checkinout> checkinouts
		{
			get
			{
				return this.GetTable<checkinout>();
			}
		}
		
		public System.Data.Linq.Table<userinfo> userinfos
		{
			get
			{
				return this.GetTable<userinfo>();
			}
		}
		
		public System.Data.Linq.Table<Sys_ParameterTemp> Sys_ParameterTemps
		{
			get
			{
				return this.GetTable<Sys_ParameterTemp>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ChamCong_DuLieuCanInsert")]
		public ISingleResult<sp_ChamCong_DuLieuCanInsertResult> sp_ChamCong_DuLieuCanInsert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> top)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), top);
			return ((ISingleResult<sp_ChamCong_DuLieuCanInsertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_XemNhanVienRaVao")]
		public ISingleResult<sp_XemNhanVienRaVaoResult> sp_XemNhanVienRaVao([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string maNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string qSearch, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> denNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> indexRowStart, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> indexRowEnd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNhanVien, qSearch, tuNgay, denNgay, indexRowStart, indexRowEnd);
			return ((ISingleResult<sp_XemNhanVienRaVaoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_XemNhanVienRaVao_Count")]
		public ISingleResult<sp_XemNhanVienRaVao_CountResult> sp_XemNhanVienRaVao_Count([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string maNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string qSearch, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> denNgay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNhanVien, qSearch, tuNgay, denNgay);
			return ((ISingleResult<sp_XemNhanVienRaVao_CountResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_XemNhanVienRaVaoNew")]
		public ISingleResult<sp_XemNhanVienRaVaoNewResult> sp_XemNhanVienRaVaoNew([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string maNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string qSearch, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> denNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> rowNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNhanVien, qSearch, tuNgay, denNgay, page, rowNumber);
			return ((ISingleResult<sp_XemNhanVienRaVaoNewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_NS_XemTinhHinhRaVao")]
		public ISingleResult<sp_NS_XemTinhHinhRaVaoResult> sp_NS_XemTinhHinhRaVao([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string maChamCong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string qSearch)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maChamCong, thang, nam, qSearch);
			return ((ISingleResult<sp_NS_XemTinhHinhRaVaoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.checkinout")]
	public partial class checkinout
	{
		
		private int _id;
		
		private System.Nullable<int> _userid;
		
		private System.Nullable<System.DateTime> _checktime;
		
		private string _checktype;
		
		private System.Nullable<int> _verifycode;
		
		private string _SN;
		
		private string _sensorid;
		
		private string _WorkCode;
		
		private string _Reserved;
		
		public checkinout()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checktime", DbType="DateTime")]
		public System.Nullable<System.DateTime> checktime
		{
			get
			{
				return this._checktime;
			}
			set
			{
				if ((this._checktime != value))
				{
					this._checktime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checktype", DbType="VarChar(1)")]
		public string checktype
		{
			get
			{
				return this._checktype;
			}
			set
			{
				if ((this._checktype != value))
				{
					this._checktype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verifycode", DbType="Int")]
		public System.Nullable<int> verifycode
		{
			get
			{
				return this._verifycode;
			}
			set
			{
				if ((this._verifycode != value))
				{
					this._verifycode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", DbType="VarChar(20)")]
		public string SN
		{
			get
			{
				return this._SN;
			}
			set
			{
				if ((this._SN != value))
				{
					this._SN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sensorid", DbType="VarChar(5)")]
		public string sensorid
		{
			get
			{
				return this._sensorid;
			}
			set
			{
				if ((this._sensorid != value))
				{
					this._sensorid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkCode", DbType="VarChar(20)")]
		public string WorkCode
		{
			get
			{
				return this._WorkCode;
			}
			set
			{
				if ((this._WorkCode != value))
				{
					this._WorkCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reserved", DbType="VarChar(20)")]
		public string Reserved
		{
			get
			{
				return this._Reserved;
			}
			set
			{
				if ((this._Reserved != value))
				{
					this._Reserved = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userinfo")]
	public partial class userinfo
	{
		
		private int _userid;
		
		private string _badgenumber;
		
		private System.Nullable<int> _defaultdeptid;
		
		private string _name;
		
		private string _Password;
		
		private string _Card;
		
		private System.Nullable<int> _Privilege;
		
		private System.Nullable<int> _AccGroup;
		
		private string _TimeZones;
		
		private string _Gender;
		
		private System.Nullable<System.DateTime> _Birthday;
		
		private string _street;
		
		private string _zip;
		
		private string _ophone;
		
		private string _FPHONE;
		
		private string _pager;
		
		private string _minzu;
		
		private string _title;
		
		private string _SN;
		
		private string _SSN;
		
		private System.Nullable<System.DateTime> _UTime;
		
		private string _State;
		
		private string _City;
		
		private System.Nullable<short> _SECURITYFLAGS;
		
		private System.Nullable<short> _DelTag;
		
		private System.Nullable<int> _RegisterOT;
		
		private System.Nullable<int> _AutoSchPlan;
		
		private System.Nullable<int> _MinAutoSchInterval;
		
		private System.Nullable<int> _Image_id;
		
		public userinfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_badgenumber", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string badgenumber
		{
			get
			{
				return this._badgenumber;
			}
			set
			{
				if ((this._badgenumber != value))
				{
					this._badgenumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_defaultdeptid", DbType="Int")]
		public System.Nullable<int> defaultdeptid
		{
			get
			{
				return this._defaultdeptid;
			}
			set
			{
				if ((this._defaultdeptid != value))
				{
					this._defaultdeptid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(40)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(20)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Card", DbType="VarChar(20)")]
		public string Card
		{
			get
			{
				return this._Card;
			}
			set
			{
				if ((this._Card != value))
				{
					this._Card = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Privilege", DbType="Int")]
		public System.Nullable<int> Privilege
		{
			get
			{
				return this._Privilege;
			}
			set
			{
				if ((this._Privilege != value))
				{
					this._Privilege = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccGroup", DbType="Int")]
		public System.Nullable<int> AccGroup
		{
			get
			{
				return this._AccGroup;
			}
			set
			{
				if ((this._AccGroup != value))
				{
					this._AccGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZones", DbType="VarChar(20)")]
		public string TimeZones
		{
			get
			{
				return this._TimeZones;
			}
			set
			{
				if ((this._TimeZones != value))
				{
					this._TimeZones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(2)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				if ((this._Birthday != value))
				{
					this._Birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street", DbType="VarChar(40)")]
		public string street
		{
			get
			{
				return this._street;
			}
			set
			{
				if ((this._street != value))
				{
					this._street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="VarChar(6)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this._zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ophone", DbType="VarChar(20)")]
		public string ophone
		{
			get
			{
				return this._ophone;
			}
			set
			{
				if ((this._ophone != value))
				{
					this._ophone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPHONE", DbType="VarChar(20)")]
		public string FPHONE
		{
			get
			{
				return this._FPHONE;
			}
			set
			{
				if ((this._FPHONE != value))
				{
					this._FPHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pager", DbType="VarChar(20)")]
		public string pager
		{
			get
			{
				return this._pager;
			}
			set
			{
				if ((this._pager != value))
				{
					this._pager = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minzu", DbType="VarChar(8)")]
		public string minzu
		{
			get
			{
				return this._minzu;
			}
			set
			{
				if ((this._minzu != value))
				{
					this._minzu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(20)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", DbType="VarChar(20)")]
		public string SN
		{
			get
			{
				return this._SN;
			}
			set
			{
				if ((this._SN != value))
				{
					this._SN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="VarChar(20)")]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this._SSN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UTime
		{
			get
			{
				return this._UTime;
			}
			set
			{
				if ((this._UTime != value))
				{
					this._UTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(2)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(2)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECURITYFLAGS", DbType="SmallInt")]
		public System.Nullable<short> SECURITYFLAGS
		{
			get
			{
				return this._SECURITYFLAGS;
			}
			set
			{
				if ((this._SECURITYFLAGS != value))
				{
					this._SECURITYFLAGS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DelTag", DbType="SmallInt")]
		public System.Nullable<short> DelTag
		{
			get
			{
				return this._DelTag;
			}
			set
			{
				if ((this._DelTag != value))
				{
					this._DelTag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterOT", DbType="Int")]
		public System.Nullable<int> RegisterOT
		{
			get
			{
				return this._RegisterOT;
			}
			set
			{
				if ((this._RegisterOT != value))
				{
					this._RegisterOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoSchPlan", DbType="Int")]
		public System.Nullable<int> AutoSchPlan
		{
			get
			{
				return this._AutoSchPlan;
			}
			set
			{
				if ((this._AutoSchPlan != value))
				{
					this._AutoSchPlan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinAutoSchInterval", DbType="Int")]
		public System.Nullable<int> MinAutoSchInterval
		{
			get
			{
				return this._MinAutoSchInterval;
			}
			set
			{
				if ((this._MinAutoSchInterval != value))
				{
					this._MinAutoSchInterval = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image_id", DbType="Int")]
		public System.Nullable<int> Image_id
		{
			get
			{
				return this._Image_id;
			}
			set
			{
				if ((this._Image_id != value))
				{
					this._Image_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sys_ParameterTemp")]
	public partial class Sys_ParameterTemp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _recordMoi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnrecordMoiChanging(System.Nullable<int> value);
    partial void OnrecordMoiChanged();
    #endregion
		
		public Sys_ParameterTemp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recordMoi", DbType="Int")]
		public System.Nullable<int> recordMoi
		{
			get
			{
				return this._recordMoi;
			}
			set
			{
				if ((this._recordMoi != value))
				{
					this.OnrecordMoiChanging(value);
					this.SendPropertyChanging();
					this._recordMoi = value;
					this.SendPropertyChanged("recordMoi");
					this.OnrecordMoiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_ChamCong_DuLieuCanInsertResult
	{
		
		private System.Nullable<System.DateTime> _checktime;
		
		private string _SN;
		
		private string _badgenumber;
		
		private int _id;
		
		public sp_ChamCong_DuLieuCanInsertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checktime", DbType="DateTime")]
		public System.Nullable<System.DateTime> checktime
		{
			get
			{
				return this._checktime;
			}
			set
			{
				if ((this._checktime != value))
				{
					this._checktime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", DbType="VarChar(20)")]
		public string SN
		{
			get
			{
				return this._SN;
			}
			set
			{
				if ((this._SN != value))
				{
					this._SN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_badgenumber", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string badgenumber
		{
			get
			{
				return this._badgenumber;
			}
			set
			{
				if ((this._badgenumber != value))
				{
					this._badgenumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
	}
	
	public partial class sp_XemNhanVienRaVaoResult
	{
		
		private System.Nullable<long> _NUMBER;
		
		private string _employeeId;
		
		private string _badgenumber;
		
		private string _fullName;
		
		private System.Nullable<System.DateTime> _checktime;
		
		private string _SN;
		
		private string _MachineName;
		
		public sp_XemNhanVienRaVaoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMBER", DbType="BigInt")]
		public System.Nullable<long> NUMBER
		{
			get
			{
				return this._NUMBER;
			}
			set
			{
				if ((this._NUMBER != value))
				{
					this._NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeId", DbType="VarChar(50)")]
		public string employeeId
		{
			get
			{
				return this._employeeId;
			}
			set
			{
				if ((this._employeeId != value))
				{
					this._employeeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_badgenumber", DbType="VarChar(50)")]
		public string badgenumber
		{
			get
			{
				return this._badgenumber;
			}
			set
			{
				if ((this._badgenumber != value))
				{
					this._badgenumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", DbType="NVarChar(150)")]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this._fullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checktime", DbType="DateTime")]
		public System.Nullable<System.DateTime> checktime
		{
			get
			{
				return this._checktime;
			}
			set
			{
				if ((this._checktime != value))
				{
					this._checktime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", DbType="VarChar(50)")]
		public string SN
		{
			get
			{
				return this._SN;
			}
			set
			{
				if ((this._SN != value))
				{
					this._SN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this._MachineName = value;
				}
			}
		}
	}
	
	public partial class sp_XemNhanVienRaVao_CountResult
	{
		
		private System.Nullable<int> _count;
		
		public sp_XemNhanVienRaVao_CountResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count", DbType="Int")]
		public System.Nullable<int> count
		{
			get
			{
				return this._count;
			}
			set
			{
				if ((this._count != value))
				{
					this._count = value;
				}
			}
		}
	}
	
	public partial class sp_XemNhanVienRaVaoNewResult
	{
		
		private System.Nullable<long> _NUMBER;
		
		private string _employeeId;
		
		private string _badgenumber;
		
		private string _fullName;
		
		private System.Nullable<System.DateTime> _checktime;
		
		private string _SN;
		
		private string _MachineName;
		
		private System.Nullable<int> _tongDong;
		
		public sp_XemNhanVienRaVaoNewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMBER", DbType="BigInt")]
		public System.Nullable<long> NUMBER
		{
			get
			{
				return this._NUMBER;
			}
			set
			{
				if ((this._NUMBER != value))
				{
					this._NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeId", DbType="VarChar(50)")]
		public string employeeId
		{
			get
			{
				return this._employeeId;
			}
			set
			{
				if ((this._employeeId != value))
				{
					this._employeeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_badgenumber", DbType="VarChar(50)")]
		public string badgenumber
		{
			get
			{
				return this._badgenumber;
			}
			set
			{
				if ((this._badgenumber != value))
				{
					this._badgenumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", DbType="NVarChar(150)")]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this._fullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checktime", DbType="DateTime")]
		public System.Nullable<System.DateTime> checktime
		{
			get
			{
				return this._checktime;
			}
			set
			{
				if ((this._checktime != value))
				{
					this._checktime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", DbType="VarChar(50)")]
		public string SN
		{
			get
			{
				return this._SN;
			}
			set
			{
				if ((this._SN != value))
				{
					this._SN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="NVarChar(150)")]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this._MachineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongDong", DbType="Int")]
		public System.Nullable<int> tongDong
		{
			get
			{
				return this._tongDong;
			}
			set
			{
				if ((this._tongDong != value))
				{
					this._tongDong = value;
				}
			}
		}
	}
	
	public partial class sp_NS_XemTinhHinhRaVaoResult
	{
		
		private string _hoTen;
		
		private string _maChamCong;
		
		private string _maNhanVien;
		
		private System.Nullable<System.DateTime> _checktime;
		
		private string _SN;
		
		public sp_NS_XemTinhHinhRaVaoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(150)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this._hoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChamCong", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string maChamCong
		{
			get
			{
				return this._maChamCong;
			}
			set
			{
				if ((this._maChamCong != value))
				{
					this._maChamCong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="VarChar(50)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this._maNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checktime", DbType="DateTime")]
		public System.Nullable<System.DateTime> checktime
		{
			get
			{
				return this._checktime;
			}
			set
			{
				if ((this._checktime != value))
				{
					this._checktime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", DbType="VarChar(20)")]
		public string SN
		{
			get
			{
				return this._SN;
			}
			set
			{
				if ((this._SN != value))
				{
					this._SN = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
