#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models.DBChamCong
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="adms_db")]
	public partial class DBChamCongDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSys_Machine(Sys_Machine instance);
    partial void UpdateSys_Machine(Sys_Machine instance);
    partial void DeleteSys_Machine(Sys_Machine instance);
    partial void InsertSys_SiteConection(Sys_SiteConection instance);
    partial void UpdateSys_SiteConection(Sys_SiteConection instance);
    partial void DeleteSys_SiteConection(Sys_SiteConection instance);
    #endregion
		
		public DBChamCongDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBChamCongDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBChamCongDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBChamCongDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sys_Machine> Sys_Machines
		{
			get
			{
				return this.GetTable<Sys_Machine>();
			}
		}
		
		public System.Data.Linq.Table<Sys_SiteConection> Sys_SiteConections
		{
			get
			{
				return this.GetTable<Sys_SiteConection>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_ViewMachinePB")]
		public ISingleResult<Sp_ViewMachinePBResult> Sp_ViewMachinePB([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maCongTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string qSearch)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongTrinh, qSearch);
			return ((ISingleResult<Sp_ViewMachinePBResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sys_Machine")]
	public partial class Sys_Machine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _siteId;
		
		private string _machineId;
		
		private string _MachineName;
		
		private string _remark;
		
		private System.Nullable<int> _typeMachine;
		
		private string _nguoiLap;
		
		private System.Nullable<System.DateTime> _ngayLap;
		
		private EntityRef<Sys_SiteConection> _Sys_SiteConection;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsiteIdChanging(string value);
    partial void OnsiteIdChanged();
    partial void OnmachineIdChanging(string value);
    partial void OnmachineIdChanged();
    partial void OnMachineNameChanging(string value);
    partial void OnMachineNameChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OntypeMachineChanging(System.Nullable<int> value);
    partial void OntypeMachineChanged();
    partial void OnnguoiLapChanging(string value);
    partial void OnnguoiLapChanged();
    partial void OnngayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapChanged();
    #endregion
		
		public Sys_Machine()
		{
			this._Sys_SiteConection = default(EntityRef<Sys_SiteConection>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					if (this._Sys_SiteConection.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machineId", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string machineId
		{
			get
			{
				return this._machineId;
			}
			set
			{
				if ((this._machineId != value))
				{
					this.OnmachineIdChanging(value);
					this.SendPropertyChanging();
					this._machineId = value;
					this.SendPropertyChanged("machineId");
					this.OnmachineIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this.OnMachineNameChanging(value);
					this.SendPropertyChanging();
					this._MachineName = value;
					this.SendPropertyChanged("MachineName");
					this.OnMachineNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NVarChar(150)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeMachine", DbType="Int")]
		public System.Nullable<int> typeMachine
		{
			get
			{
				return this._typeMachine;
			}
			set
			{
				if ((this._typeMachine != value))
				{
					this.OntypeMachineChanging(value);
					this.SendPropertyChanging();
					this._typeMachine = value;
					this.SendPropertyChanged("typeMachine");
					this.OntypeMachineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiLap", DbType="NVarChar(100)")]
		public string nguoiLap
		{
			get
			{
				return this._nguoiLap;
			}
			set
			{
				if ((this._nguoiLap != value))
				{
					this.OnnguoiLapChanging(value);
					this.SendPropertyChanging();
					this._nguoiLap = value;
					this.SendPropertyChanged("nguoiLap");
					this.OnnguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sys_SiteConection_Sys_Machine", Storage="_Sys_SiteConection", ThisKey="siteId", OtherKey="siteId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Sys_SiteConection Sys_SiteConection
		{
			get
			{
				return this._Sys_SiteConection.Entity;
			}
			set
			{
				Sys_SiteConection previousValue = this._Sys_SiteConection.Entity;
				if (((previousValue != value) 
							|| (this._Sys_SiteConection.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sys_SiteConection.Entity = null;
						previousValue.Sys_Machines.Remove(this);
					}
					this._Sys_SiteConection.Entity = value;
					if ((value != null))
					{
						value.Sys_Machines.Add(this);
						this._siteId = value.siteId;
					}
					else
					{
						this._siteId = default(string);
					}
					this.SendPropertyChanged("Sys_SiteConection");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sys_SiteConection")]
	public partial class Sys_SiteConection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _siteId;
		
		private string _siteName;
		
		private string _siteAddress;
		
		private string _siteIP;
		
		private string _port;
		
		private string _loginName;
		
		private string _pdw;
		
		private string _databaseName;
		
		private string _remark;
		
		private string _nguoiLap;
		
		private System.Nullable<System.DateTime> _ngayLap;
		
		private EntitySet<Sys_Machine> _Sys_Machines;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsiteIdChanging(string value);
    partial void OnsiteIdChanged();
    partial void OnsiteNameChanging(string value);
    partial void OnsiteNameChanged();
    partial void OnsiteAddressChanging(string value);
    partial void OnsiteAddressChanged();
    partial void OnsiteIPChanging(string value);
    partial void OnsiteIPChanged();
    partial void OnportChanging(string value);
    partial void OnportChanged();
    partial void OnloginNameChanging(string value);
    partial void OnloginNameChanged();
    partial void OnpdwChanging(string value);
    partial void OnpdwChanged();
    partial void OndatabaseNameChanging(string value);
    partial void OndatabaseNameChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OnnguoiLapChanging(string value);
    partial void OnnguoiLapChanged();
    partial void OnngayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapChanged();
    #endregion
		
		public Sys_SiteConection()
		{
			this._Sys_Machines = new EntitySet<Sys_Machine>(new Action<Sys_Machine>(this.attach_Sys_Machines), new Action<Sys_Machine>(this.detach_Sys_Machines));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string siteName
		{
			get
			{
				return this._siteName;
			}
			set
			{
				if ((this._siteName != value))
				{
					this.OnsiteNameChanging(value);
					this.SendPropertyChanging();
					this._siteName = value;
					this.SendPropertyChanged("siteName");
					this.OnsiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteAddress", DbType="NVarChar(150)")]
		public string siteAddress
		{
			get
			{
				return this._siteAddress;
			}
			set
			{
				if ((this._siteAddress != value))
				{
					this.OnsiteAddressChanging(value);
					this.SendPropertyChanging();
					this._siteAddress = value;
					this.SendPropertyChanged("siteAddress");
					this.OnsiteAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteIP", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string siteIP
		{
			get
			{
				return this._siteIP;
			}
			set
			{
				if ((this._siteIP != value))
				{
					this.OnsiteIPChanging(value);
					this.SendPropertyChanging();
					this._siteIP = value;
					this.SendPropertyChanged("siteIP");
					this.OnsiteIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_port", DbType="VarChar(7)")]
		public string port
		{
			get
			{
				return this._port;
			}
			set
			{
				if ((this._port != value))
				{
					this.OnportChanging(value);
					this.SendPropertyChanging();
					this._port = value;
					this.SendPropertyChanged("port");
					this.OnportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loginName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string loginName
		{
			get
			{
				return this._loginName;
			}
			set
			{
				if ((this._loginName != value))
				{
					this.OnloginNameChanging(value);
					this.SendPropertyChanging();
					this._loginName = value;
					this.SendPropertyChanged("loginName");
					this.OnloginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdw", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string pdw
		{
			get
			{
				return this._pdw;
			}
			set
			{
				if ((this._pdw != value))
				{
					this.OnpdwChanging(value);
					this.SendPropertyChanging();
					this._pdw = value;
					this.SendPropertyChanged("pdw");
					this.OnpdwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_databaseName", DbType="VarChar(30)")]
		public string databaseName
		{
			get
			{
				return this._databaseName;
			}
			set
			{
				if ((this._databaseName != value))
				{
					this.OndatabaseNameChanging(value);
					this.SendPropertyChanging();
					this._databaseName = value;
					this.SendPropertyChanged("databaseName");
					this.OndatabaseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NVarChar(250)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiLap", DbType="NVarChar(100)")]
		public string nguoiLap
		{
			get
			{
				return this._nguoiLap;
			}
			set
			{
				if ((this._nguoiLap != value))
				{
					this.OnnguoiLapChanging(value);
					this.SendPropertyChanging();
					this._nguoiLap = value;
					this.SendPropertyChanged("nguoiLap");
					this.OnnguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sys_SiteConection_Sys_Machine", Storage="_Sys_Machines", ThisKey="siteId", OtherKey="siteId")]
		public EntitySet<Sys_Machine> Sys_Machines
		{
			get
			{
				return this._Sys_Machines;
			}
			set
			{
				this._Sys_Machines.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sys_Machines(Sys_Machine entity)
		{
			this.SendPropertyChanging();
			entity.Sys_SiteConection = this;
		}
		
		private void detach_Sys_Machines(Sys_Machine entity)
		{
			this.SendPropertyChanging();
			entity.Sys_SiteConection = null;
		}
	}
	
	public partial class Sp_ViewMachinePBResult
	{
		
		private string _siteId;
		
		private string _machineId;
		
		private string _MachineName;
		
		private string _remark;
		
		private System.Nullable<int> _typeMachine;
		
		private string _siteName;
		
		private int _trangThai;
		
		private System.Nullable<System.DateTime> _LastActivity;
		
		private string _IPAddress;
		
		private System.Nullable<int> _FPCount;
		
		private System.Nullable<int> _TransactionCount;
		
		private System.Nullable<int> _UserCount;
		
		public Sp_ViewMachinePBResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this._siteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machineId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string machineId
		{
			get
			{
				return this._machineId;
			}
			set
			{
				if ((this._machineId != value))
				{
					this._machineId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this._MachineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NVarChar(150)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this._remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeMachine", DbType="Int")]
		public System.Nullable<int> typeMachine
		{
			get
			{
				return this._typeMachine;
			}
			set
			{
				if ((this._typeMachine != value))
				{
					this._typeMachine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteName", DbType="NVarChar(100)")]
		public string siteName
		{
			get
			{
				return this._siteName;
			}
			set
			{
				if ((this._siteName != value))
				{
					this._siteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int NOT NULL")]
		public int trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this._trangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivity", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastActivity
		{
			get
			{
				return this._LastActivity;
			}
			set
			{
				if ((this._LastActivity != value))
				{
					this._LastActivity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="VarChar(20)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this._IPAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPCount", DbType="Int")]
		public System.Nullable<int> FPCount
		{
			get
			{
				return this._FPCount;
			}
			set
			{
				if ((this._FPCount != value))
				{
					this._FPCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionCount", DbType="Int")]
		public System.Nullable<int> TransactionCount
		{
			get
			{
				return this._TransactionCount;
			}
			set
			{
				if ((this._TransactionCount != value))
				{
					this._TransactionCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCount", DbType="Int")]
		public System.Nullable<int> UserCount
		{
			get
			{
				return this._UserCount;
			}
			set
			{
				if ((this._UserCount != value))
				{
					this._UserCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
