#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models.NhanSuService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NhanSuService")]
	public partial class NSServiceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSys_ThongBao(Sys_ThongBao instance);
    partial void UpdateSys_ThongBao(Sys_ThongBao instance);
    partial void DeleteSys_ThongBao(Sys_ThongBao instance);
    partial void InsertSys_User_ThongBao(Sys_User_ThongBao instance);
    partial void UpdateSys_User_ThongBao(Sys_User_ThongBao instance);
    partial void DeleteSys_User_ThongBao(Sys_User_ThongBao instance);
    partial void Inserttbl_FileDinhKem(tbl_FileDinhKem instance);
    partial void Updatetbl_FileDinhKem(tbl_FileDinhKem instance);
    partial void Deletetbl_FileDinhKem(tbl_FileDinhKem instance);
    partial void InsertSys_EmailGuiThongBao(Sys_EmailGuiThongBao instance);
    partial void UpdateSys_EmailGuiThongBao(Sys_EmailGuiThongBao instance);
    partial void DeleteSys_EmailGuiThongBao(Sys_EmailGuiThongBao instance);
    #endregion
		
		public NSServiceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NSServiceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NSServiceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NSServiceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sys_ThongBao> Sys_ThongBaos
		{
			get
			{
				return this.GetTable<Sys_ThongBao>();
			}
		}
		
		public System.Data.Linq.Table<Sys_User_ThongBao> Sys_User_ThongBaos
		{
			get
			{
				return this.GetTable<Sys_User_ThongBao>();
			}
		}
		
		public System.Data.Linq.Table<tbl_FileDinhKem> tbl_FileDinhKems
		{
			get
			{
				return this.GetTable<tbl_FileDinhKem>();
			}
		}
		
		public System.Data.Linq.Table<Sys_EmailGuiThongBao> Sys_EmailGuiThongBaos
		{
			get
			{
				return this.GetTable<Sys_EmailGuiThongBao>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sys_ThongBao")]
	public partial class Sys_ThongBao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _tenThongBao;
		
		private string _maPhongBan;
		
		private string _noiDungThongBao;
		
		private System.Nullable<System.DateTime> _ngayLap;
		
		private string _nguoiLap;
		
		private string _listCapBac;
		
		private string _listNhanVien;
		
		private string _listPhongBan;
		
		private System.Nullable<bool> _daGuiEmail;
		
		private string _noiDungSMS;
		
		private System.Nullable<bool> _daGuiSMS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenThongBaoChanging(string value);
    partial void OntenThongBaoChanged();
    partial void OnmaPhongBanChanging(string value);
    partial void OnmaPhongBanChanged();
    partial void OnnoiDungThongBaoChanging(string value);
    partial void OnnoiDungThongBaoChanged();
    partial void OnngayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapChanged();
    partial void OnnguoiLapChanging(string value);
    partial void OnnguoiLapChanged();
    partial void OnlistCapBacChanging(string value);
    partial void OnlistCapBacChanged();
    partial void OnlistNhanVienChanging(string value);
    partial void OnlistNhanVienChanged();
    partial void OnlistPhongBanChanging(string value);
    partial void OnlistPhongBanChanged();
    partial void OndaGuiEmailChanging(System.Nullable<bool> value);
    partial void OndaGuiEmailChanged();
    partial void OnnoiDungSMSChanging(string value);
    partial void OnnoiDungSMSChanged();
    partial void OndaGuiSMSChanging(System.Nullable<bool> value);
    partial void OndaGuiSMSChanged();
    #endregion
		
		public Sys_ThongBao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenThongBao", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string tenThongBao
		{
			get
			{
				return this._tenThongBao;
			}
			set
			{
				if ((this._tenThongBao != value))
				{
					this.OntenThongBaoChanging(value);
					this.SendPropertyChanging();
					this._tenThongBao = value;
					this.SendPropertyChanged("tenThongBao");
					this.OntenThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhongBan", DbType="NVarChar(200)")]
		public string maPhongBan
		{
			get
			{
				return this._maPhongBan;
			}
			set
			{
				if ((this._maPhongBan != value))
				{
					this.OnmaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._maPhongBan = value;
					this.SendPropertyChanged("maPhongBan");
					this.OnmaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDungThongBao", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string noiDungThongBao
		{
			get
			{
				return this._noiDungThongBao;
			}
			set
			{
				if ((this._noiDungThongBao != value))
				{
					this.OnnoiDungThongBaoChanging(value);
					this.SendPropertyChanging();
					this._noiDungThongBao = value;
					this.SendPropertyChanged("noiDungThongBao");
					this.OnnoiDungThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiLap", DbType="VarChar(50)")]
		public string nguoiLap
		{
			get
			{
				return this._nguoiLap;
			}
			set
			{
				if ((this._nguoiLap != value))
				{
					this.OnnguoiLapChanging(value);
					this.SendPropertyChanging();
					this._nguoiLap = value;
					this.SendPropertyChanged("nguoiLap");
					this.OnnguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_listCapBac", DbType="NVarChar(500)")]
		public string listCapBac
		{
			get
			{
				return this._listCapBac;
			}
			set
			{
				if ((this._listCapBac != value))
				{
					this.OnlistCapBacChanging(value);
					this.SendPropertyChanging();
					this._listCapBac = value;
					this.SendPropertyChanged("listCapBac");
					this.OnlistCapBacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_listNhanVien", DbType="NVarChar(500)")]
		public string listNhanVien
		{
			get
			{
				return this._listNhanVien;
			}
			set
			{
				if ((this._listNhanVien != value))
				{
					this.OnlistNhanVienChanging(value);
					this.SendPropertyChanging();
					this._listNhanVien = value;
					this.SendPropertyChanged("listNhanVien");
					this.OnlistNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_listPhongBan", DbType="NVarChar(500)")]
		public string listPhongBan
		{
			get
			{
				return this._listPhongBan;
			}
			set
			{
				if ((this._listPhongBan != value))
				{
					this.OnlistPhongBanChanging(value);
					this.SendPropertyChanging();
					this._listPhongBan = value;
					this.SendPropertyChanged("listPhongBan");
					this.OnlistPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daGuiEmail", DbType="Bit")]
		public System.Nullable<bool> daGuiEmail
		{
			get
			{
				return this._daGuiEmail;
			}
			set
			{
				if ((this._daGuiEmail != value))
				{
					this.OndaGuiEmailChanging(value);
					this.SendPropertyChanging();
					this._daGuiEmail = value;
					this.SendPropertyChanged("daGuiEmail");
					this.OndaGuiEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDungSMS", DbType="NVarChar(500)")]
		public string noiDungSMS
		{
			get
			{
				return this._noiDungSMS;
			}
			set
			{
				if ((this._noiDungSMS != value))
				{
					this.OnnoiDungSMSChanging(value);
					this.SendPropertyChanging();
					this._noiDungSMS = value;
					this.SendPropertyChanged("noiDungSMS");
					this.OnnoiDungSMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daGuiSMS", DbType="Bit")]
		public System.Nullable<bool> daGuiSMS
		{
			get
			{
				return this._daGuiSMS;
			}
			set
			{
				if ((this._daGuiSMS != value))
				{
					this.OndaGuiSMSChanging(value);
					this.SendPropertyChanging();
					this._daGuiSMS = value;
					this.SendPropertyChanged("daGuiSMS");
					this.OndaGuiSMSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sys_User_ThongBao")]
	public partial class Sys_User_ThongBao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _manv;
		
		private System.Nullable<int> _idThongBao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnidThongBaoChanging(System.Nullable<int> value);
    partial void OnidThongBaoChanged();
    #endregion
		
		public Sys_User_ThongBao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(20)")]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idThongBao", DbType="Int")]
		public System.Nullable<int> idThongBao
		{
			get
			{
				return this._idThongBao;
			}
			set
			{
				if ((this._idThongBao != value))
				{
					this.OnidThongBaoChanging(value);
					this.SendPropertyChanging();
					this._idThongBao = value;
					this.SendPropertyChanged("idThongBao");
					this.OnidThongBaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_FileDinhKem")]
	public partial class tbl_FileDinhKem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _controller;
		
		private string _Action;
		
		private string _identification;
		
		private string _contentType;
		
		private string _originalFileName;
		
		private string _savedFileName;
		
		private string _maNguoiUpLoad;
		
		private string _tenNguoiUpLoad;
		
		private System.Nullable<System.DateTime> _ngayLap;
		
		private string _taiLieuURL;
		
		private string _thumbnailURL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncontrollerChanging(string value);
    partial void OncontrollerChanged();
    partial void OnActionChanging(string value);
    partial void OnActionChanged();
    partial void OnidentificationChanging(string value);
    partial void OnidentificationChanged();
    partial void OncontentTypeChanging(string value);
    partial void OncontentTypeChanged();
    partial void OnoriginalFileNameChanging(string value);
    partial void OnoriginalFileNameChanged();
    partial void OnsavedFileNameChanging(string value);
    partial void OnsavedFileNameChanged();
    partial void OnmaNguoiUpLoadChanging(string value);
    partial void OnmaNguoiUpLoadChanged();
    partial void OntenNguoiUpLoadChanging(string value);
    partial void OntenNguoiUpLoadChanged();
    partial void OnngayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapChanged();
    partial void OntaiLieuURLChanging(string value);
    partial void OntaiLieuURLChanged();
    partial void OnthumbnailURLChanging(string value);
    partial void OnthumbnailURLChanged();
    #endregion
		
		public tbl_FileDinhKem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_controller", DbType="VarChar(200)")]
		public string controller
		{
			get
			{
				return this._controller;
			}
			set
			{
				if ((this._controller != value))
				{
					this.OncontrollerChanging(value);
					this.SendPropertyChanging();
					this._controller = value;
					this.SendPropertyChanged("controller");
					this.OncontrollerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action", DbType="VarChar(50)")]
		public string Action
		{
			get
			{
				return this._Action;
			}
			set
			{
				if ((this._Action != value))
				{
					this.OnActionChanging(value);
					this.SendPropertyChanging();
					this._Action = value;
					this.SendPropertyChanged("Action");
					this.OnActionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identification", DbType="VarChar(50)")]
		public string identification
		{
			get
			{
				return this._identification;
			}
			set
			{
				if ((this._identification != value))
				{
					this.OnidentificationChanging(value);
					this.SendPropertyChanging();
					this._identification = value;
					this.SendPropertyChanged("identification");
					this.OnidentificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contentType", DbType="VarChar(200)")]
		public string contentType
		{
			get
			{
				return this._contentType;
			}
			set
			{
				if ((this._contentType != value))
				{
					this.OncontentTypeChanging(value);
					this.SendPropertyChanging();
					this._contentType = value;
					this.SendPropertyChanged("contentType");
					this.OncontentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_originalFileName", DbType="NVarChar(500)")]
		public string originalFileName
		{
			get
			{
				return this._originalFileName;
			}
			set
			{
				if ((this._originalFileName != value))
				{
					this.OnoriginalFileNameChanging(value);
					this.SendPropertyChanging();
					this._originalFileName = value;
					this.SendPropertyChanged("originalFileName");
					this.OnoriginalFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_savedFileName", DbType="NVarChar(500)")]
		public string savedFileName
		{
			get
			{
				return this._savedFileName;
			}
			set
			{
				if ((this._savedFileName != value))
				{
					this.OnsavedFileNameChanging(value);
					this.SendPropertyChanging();
					this._savedFileName = value;
					this.SendPropertyChanged("savedFileName");
					this.OnsavedFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNguoiUpLoad", DbType="VarChar(50)")]
		public string maNguoiUpLoad
		{
			get
			{
				return this._maNguoiUpLoad;
			}
			set
			{
				if ((this._maNguoiUpLoad != value))
				{
					this.OnmaNguoiUpLoadChanging(value);
					this.SendPropertyChanging();
					this._maNguoiUpLoad = value;
					this.SendPropertyChanged("maNguoiUpLoad");
					this.OnmaNguoiUpLoadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNguoiUpLoad", DbType="NVarChar(200)")]
		public string tenNguoiUpLoad
		{
			get
			{
				return this._tenNguoiUpLoad;
			}
			set
			{
				if ((this._tenNguoiUpLoad != value))
				{
					this.OntenNguoiUpLoadChanging(value);
					this.SendPropertyChanging();
					this._tenNguoiUpLoad = value;
					this.SendPropertyChanged("tenNguoiUpLoad");
					this.OntenNguoiUpLoadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taiLieuURL", DbType="NVarChar(500)")]
		public string taiLieuURL
		{
			get
			{
				return this._taiLieuURL;
			}
			set
			{
				if ((this._taiLieuURL != value))
				{
					this.OntaiLieuURLChanging(value);
					this.SendPropertyChanging();
					this._taiLieuURL = value;
					this.SendPropertyChanged("taiLieuURL");
					this.OntaiLieuURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thumbnailURL", DbType="NVarChar(500)")]
		public string thumbnailURL
		{
			get
			{
				return this._thumbnailURL;
			}
			set
			{
				if ((this._thumbnailURL != value))
				{
					this.OnthumbnailURLChanging(value);
					this.SendPropertyChanging();
					this._thumbnailURL = value;
					this.SendPropertyChanged("thumbnailURL");
					this.OnthumbnailURLChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sys_EmailGuiThongBao")]
	public partial class Sys_EmailGuiThongBao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idThongBao;
		
		private System.DateTime _ngayGui;
		
		private string _tieuDe;
		
		private string _noiDung;
		
		private string _nguoiGui;
		
		private System.Nullable<bool> _trangThaiGui;
		
		private string _emailGuiDen;
		
		private string _maNhanVien;
		
		private string _titleMail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidThongBaoChanging(int value);
    partial void OnidThongBaoChanged();
    partial void OnngayGuiChanging(System.DateTime value);
    partial void OnngayGuiChanged();
    partial void OntieuDeChanging(string value);
    partial void OntieuDeChanged();
    partial void OnnoiDungChanging(string value);
    partial void OnnoiDungChanged();
    partial void OnnguoiGuiChanging(string value);
    partial void OnnguoiGuiChanged();
    partial void OntrangThaiGuiChanging(System.Nullable<bool> value);
    partial void OntrangThaiGuiChanged();
    partial void OnemailGuiDenChanging(string value);
    partial void OnemailGuiDenChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OntitleMailChanging(string value);
    partial void OntitleMailChanged();
    #endregion
		
		public Sys_EmailGuiThongBao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idThongBao", DbType="Int NOT NULL")]
		public int idThongBao
		{
			get
			{
				return this._idThongBao;
			}
			set
			{
				if ((this._idThongBao != value))
				{
					this.OnidThongBaoChanging(value);
					this.SendPropertyChanging();
					this._idThongBao = value;
					this.SendPropertyChanged("idThongBao");
					this.OnidThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayGui", DbType="DateTime NOT NULL")]
		public System.DateTime ngayGui
		{
			get
			{
				return this._ngayGui;
			}
			set
			{
				if ((this._ngayGui != value))
				{
					this.OnngayGuiChanging(value);
					this.SendPropertyChanging();
					this._ngayGui = value;
					this.SendPropertyChanged("ngayGui");
					this.OnngayGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieuDe", DbType="NVarChar(300)")]
		public string tieuDe
		{
			get
			{
				return this._tieuDe;
			}
			set
			{
				if ((this._tieuDe != value))
				{
					this.OntieuDeChanging(value);
					this.SendPropertyChanging();
					this._tieuDe = value;
					this.SendPropertyChanged("tieuDe");
					this.OntieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string noiDung
		{
			get
			{
				return this._noiDung;
			}
			set
			{
				if ((this._noiDung != value))
				{
					this.OnnoiDungChanging(value);
					this.SendPropertyChanging();
					this._noiDung = value;
					this.SendPropertyChanged("noiDung");
					this.OnnoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiGui", DbType="VarChar(50)")]
		public string nguoiGui
		{
			get
			{
				return this._nguoiGui;
			}
			set
			{
				if ((this._nguoiGui != value))
				{
					this.OnnguoiGuiChanging(value);
					this.SendPropertyChanging();
					this._nguoiGui = value;
					this.SendPropertyChanged("nguoiGui");
					this.OnnguoiGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThaiGui", DbType="Bit")]
		public System.Nullable<bool> trangThaiGui
		{
			get
			{
				return this._trangThaiGui;
			}
			set
			{
				if ((this._trangThaiGui != value))
				{
					this.OntrangThaiGuiChanging(value);
					this.SendPropertyChanging();
					this._trangThaiGui = value;
					this.SendPropertyChanged("trangThaiGui");
					this.OntrangThaiGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailGuiDen", DbType="NVarChar(300)")]
		public string emailGuiDen
		{
			get
			{
				return this._emailGuiDen;
			}
			set
			{
				if ((this._emailGuiDen != value))
				{
					this.OnemailGuiDenChanging(value);
					this.SendPropertyChanging();
					this._emailGuiDen = value;
					this.SendPropertyChanged("emailGuiDen");
					this.OnemailGuiDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titleMail", DbType="NVarChar(300)")]
		public string titleMail
		{
			get
			{
				return this._titleMail;
			}
			set
			{
				if ((this._titleMail != value))
				{
					this.OntitleMailChanging(value);
					this.SendPropertyChanging();
					this._titleMail = value;
					this.SendPropertyChanged("titleMail");
					this.OntitleMailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
