#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models.NhanSu.NhanSuThuanViet
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="nhanSuThuanViet")]
	public partial class HRThuanVietDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_NS_ChamCong(tbl_NS_ChamCong instance);
    partial void Updatetbl_NS_ChamCong(tbl_NS_ChamCong instance);
    partial void Deletetbl_NS_ChamCong(tbl_NS_ChamCong instance);
    #endregion
		
		public HRThuanVietDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRThuanVietDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRThuanVietDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRThuanVietDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_NS_ChamCong> tbl_NS_ChamCongs
		{
			get
			{
				return this.GetTable<tbl_NS_ChamCong>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NS_ChamCong")]
	public partial class tbl_NS_ChamCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _checkTime;
		
		private string _maMayChamCong;
		
		private string _maChamCong;
		
		private System.Nullable<int> _idQuet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncheckTimeChanging(System.Nullable<System.DateTime> value);
    partial void OncheckTimeChanged();
    partial void OnmaMayChamCongChanging(string value);
    partial void OnmaMayChamCongChanged();
    partial void OnmaChamCongChanging(string value);
    partial void OnmaChamCongChanged();
    partial void OnidQuetChanging(System.Nullable<int> value);
    partial void OnidQuetChanged();
    #endregion
		
		public tbl_NS_ChamCong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> checkTime
		{
			get
			{
				return this._checkTime;
			}
			set
			{
				if ((this._checkTime != value))
				{
					this.OncheckTimeChanging(value);
					this.SendPropertyChanging();
					this._checkTime = value;
					this.SendPropertyChanged("checkTime");
					this.OncheckTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMayChamCong", DbType="VarChar(50)")]
		public string maMayChamCong
		{
			get
			{
				return this._maMayChamCong;
			}
			set
			{
				if ((this._maMayChamCong != value))
				{
					this.OnmaMayChamCongChanging(value);
					this.SendPropertyChanging();
					this._maMayChamCong = value;
					this.SendPropertyChanged("maMayChamCong");
					this.OnmaMayChamCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChamCong", DbType="VarChar(50)")]
		public string maChamCong
		{
			get
			{
				return this._maChamCong;
			}
			set
			{
				if ((this._maChamCong != value))
				{
					this.OnmaChamCongChanging(value);
					this.SendPropertyChanging();
					this._maChamCong = value;
					this.SendPropertyChanged("maChamCong");
					this.OnmaChamCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idQuet", DbType="Int")]
		public System.Nullable<int> idQuet
		{
			get
			{
				return this._idQuet;
			}
			set
			{
				if ((this._idQuet != value))
				{
					this.OnidQuetChanging(value);
					this.SendPropertyChanging();
					this._idQuet = value;
					this.SendPropertyChanged("idQuet");
					this.OnidQuetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
