#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models.NhanSu.LinqCT2220
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ERP_TV")]
	public partial class LinqCT2220DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_QuiTrinhDuyet_BuocDuyet(tbl_QuiTrinhDuyet_BuocDuyet instance);
    partial void Updatetbl_QuiTrinhDuyet_BuocDuyet(tbl_QuiTrinhDuyet_BuocDuyet instance);
    partial void Deletetbl_QuiTrinhDuyet_BuocDuyet(tbl_QuiTrinhDuyet_BuocDuyet instance);
    partial void Inserttbl_DeNghiChiLuong(tbl_DeNghiChiLuong instance);
    partial void Updatetbl_DeNghiChiLuong(tbl_DeNghiChiLuong instance);
    partial void Deletetbl_DeNghiChiLuong(tbl_DeNghiChiLuong instance);
    partial void InsertHT_DMNguoiDuyet(HT_DMNguoiDuyet instance);
    partial void UpdateHT_DMNguoiDuyet(HT_DMNguoiDuyet instance);
    partial void DeleteHT_DMNguoiDuyet(HT_DMNguoiDuyet instance);
    partial void Inserttbl_DeNghiChiLuongChiTiet(tbl_DeNghiChiLuongChiTiet instance);
    partial void Updatetbl_DeNghiChiLuongChiTiet(tbl_DeNghiChiLuongChiTiet instance);
    partial void Deletetbl_DeNghiChiLuongChiTiet(tbl_DeNghiChiLuongChiTiet instance);
    #endregion
		
		public LinqCT2220DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqCT2220DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqCT2220DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqCT2220DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_QuiTrinhDuyet_BuocDuyet> tbl_QuiTrinhDuyet_BuocDuyets
		{
			get
			{
				return this.GetTable<tbl_QuiTrinhDuyet_BuocDuyet>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DeNghiChiLuong> tbl_DeNghiChiLuongs
		{
			get
			{
				return this.GetTable<tbl_DeNghiChiLuong>();
			}
		}
		
		public System.Data.Linq.Table<HT_DMNguoiDuyet> HT_DMNguoiDuyets
		{
			get
			{
				return this.GetTable<HT_DMNguoiDuyet>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DeNghiChiLuongChiTiet> tbl_DeNghiChiLuongChiTiets
		{
			get
			{
				return this.GetTable<tbl_DeNghiChiLuongChiTiet>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_QuiTrinhDuyetAS")]
		public ISingleResult<sp_QuiTrinhDuyetASResult> sp_QuiTrinhDuyetAS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maCongViec)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongViec);
			return ((ISingleResult<sp_QuiTrinhDuyetASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_QuiTrinhDuyet_TrangTiepTheo")]
		public ISingleResult<sp_QuiTrinhDuyet_TrangTiepTheoResult> sp_QuiTrinhDuyet_TrangTiepTheo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maQuiTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maPhieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maQuiTrinh, maPhieu, flag);
			return ((ISingleResult<sp_QuiTrinhDuyet_TrangTiepTheoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_QuiTrinhDuyet_BuocDuyet")]
	public partial class tbl_QuiTrinhDuyet_BuocDuyet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MaBuocDuyet;
		
		private string _TenBuocDuyet;
		
		private string _GhiChu;
		
		private string _TenHienThiFooter;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMaBuocDuyetChanging(string value);
    partial void OnMaBuocDuyetChanged();
    partial void OnTenBuocDuyetChanging(string value);
    partial void OnTenBuocDuyetChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnTenHienThiFooterChanging(string value);
    partial void OnTenHienThiFooterChanged();
    #endregion
		
		public tbl_QuiTrinhDuyet_BuocDuyet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBuocDuyet", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBuocDuyet
		{
			get
			{
				return this._MaBuocDuyet;
			}
			set
			{
				if ((this._MaBuocDuyet != value))
				{
					this.OnMaBuocDuyetChanging(value);
					this.SendPropertyChanging();
					this._MaBuocDuyet = value;
					this.SendPropertyChanged("MaBuocDuyet");
					this.OnMaBuocDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBuocDuyet", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string TenBuocDuyet
		{
			get
			{
				return this._TenBuocDuyet;
			}
			set
			{
				if ((this._TenBuocDuyet != value))
				{
					this.OnTenBuocDuyetChanging(value);
					this.SendPropertyChanging();
					this._TenBuocDuyet = value;
					this.SendPropertyChanged("TenBuocDuyet");
					this.OnTenBuocDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(150)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHienThiFooter", DbType="NVarChar(250)")]
		public string TenHienThiFooter
		{
			get
			{
				return this._TenHienThiFooter;
			}
			set
			{
				if ((this._TenHienThiFooter != value))
				{
					this.OnTenHienThiFooterChanging(value);
					this.SendPropertyChanging();
					this._TenHienThiFooter = value;
					this.SendPropertyChanged("TenHienThiFooter");
					this.OnTenHienThiFooterChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DeNghiChiLuong")]
	public partial class tbl_DeNghiChiLuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPhieu;
		
		private System.Nullable<System.DateTime> _ngayLap;
		
		private System.Nullable<int> _thang;
		
		private System.Nullable<int> _nam;
		
		private string _nguoiLap;
		
		private string _noiDung;
		
		private System.Nullable<int> _maQuiTrinhDuyet;
		
		private string _tenNguoiLap;
		
		private string _doiTuongBH;
		
		private string _doiTuongThue;
		
		private string _doiTuongLuong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhieuChanging(string value);
    partial void OnmaPhieuChanged();
    partial void OnngayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapChanged();
    partial void OnthangChanging(System.Nullable<int> value);
    partial void OnthangChanged();
    partial void OnnamChanging(System.Nullable<int> value);
    partial void OnnamChanged();
    partial void OnnguoiLapChanging(string value);
    partial void OnnguoiLapChanged();
    partial void OnnoiDungChanging(string value);
    partial void OnnoiDungChanged();
    partial void OnmaQuiTrinhDuyetChanging(System.Nullable<int> value);
    partial void OnmaQuiTrinhDuyetChanged();
    partial void OntenNguoiLapChanging(string value);
    partial void OntenNguoiLapChanged();
    partial void OndoiTuongBHChanging(string value);
    partial void OndoiTuongBHChanged();
    partial void OndoiTuongThueChanging(string value);
    partial void OndoiTuongThueChanged();
    partial void OndoiTuongLuongChanging(string value);
    partial void OndoiTuongLuongChanged();
    #endregion
		
		public tbl_DeNghiChiLuong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieu", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhieu
		{
			get
			{
				return this._maPhieu;
			}
			set
			{
				if ((this._maPhieu != value))
				{
					this.OnmaPhieuChanging(value);
					this.SendPropertyChanging();
					this._maPhieu = value;
					this.SendPropertyChanged("maPhieu");
					this.OnmaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thang", DbType="Int")]
		public System.Nullable<int> thang
		{
			get
			{
				return this._thang;
			}
			set
			{
				if ((this._thang != value))
				{
					this.OnthangChanging(value);
					this.SendPropertyChanging();
					this._thang = value;
					this.SendPropertyChanged("thang");
					this.OnthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="Int")]
		public System.Nullable<int> nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this.OnnamChanging(value);
					this.SendPropertyChanging();
					this._nam = value;
					this.SendPropertyChanged("nam");
					this.OnnamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiLap", DbType="VarChar(50)")]
		public string nguoiLap
		{
			get
			{
				return this._nguoiLap;
			}
			set
			{
				if ((this._nguoiLap != value))
				{
					this.OnnguoiLapChanging(value);
					this.SendPropertyChanging();
					this._nguoiLap = value;
					this.SendPropertyChanged("nguoiLap");
					this.OnnguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDung", DbType="NVarChar(MAX)")]
		public string noiDung
		{
			get
			{
				return this._noiDung;
			}
			set
			{
				if ((this._noiDung != value))
				{
					this.OnnoiDungChanging(value);
					this.SendPropertyChanging();
					this._noiDung = value;
					this.SendPropertyChanged("noiDung");
					this.OnnoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maQuiTrinhDuyet", DbType="Int")]
		public System.Nullable<int> maQuiTrinhDuyet
		{
			get
			{
				return this._maQuiTrinhDuyet;
			}
			set
			{
				if ((this._maQuiTrinhDuyet != value))
				{
					this.OnmaQuiTrinhDuyetChanging(value);
					this.SendPropertyChanging();
					this._maQuiTrinhDuyet = value;
					this.SendPropertyChanged("maQuiTrinhDuyet");
					this.OnmaQuiTrinhDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNguoiLap", DbType="NVarChar(150)")]
		public string tenNguoiLap
		{
			get
			{
				return this._tenNguoiLap;
			}
			set
			{
				if ((this._tenNguoiLap != value))
				{
					this.OntenNguoiLapChanging(value);
					this.SendPropertyChanging();
					this._tenNguoiLap = value;
					this.SendPropertyChanged("tenNguoiLap");
					this.OntenNguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doiTuongBH", DbType="VarChar(30)")]
		public string doiTuongBH
		{
			get
			{
				return this._doiTuongBH;
			}
			set
			{
				if ((this._doiTuongBH != value))
				{
					this.OndoiTuongBHChanging(value);
					this.SendPropertyChanging();
					this._doiTuongBH = value;
					this.SendPropertyChanged("doiTuongBH");
					this.OndoiTuongBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doiTuongThue", DbType="VarChar(30)")]
		public string doiTuongThue
		{
			get
			{
				return this._doiTuongThue;
			}
			set
			{
				if ((this._doiTuongThue != value))
				{
					this.OndoiTuongThueChanging(value);
					this.SendPropertyChanging();
					this._doiTuongThue = value;
					this.SendPropertyChanged("doiTuongThue");
					this.OndoiTuongThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doiTuongLuong", DbType="VarChar(30)")]
		public string doiTuongLuong
		{
			get
			{
				return this._doiTuongLuong;
			}
			set
			{
				if ((this._doiTuongLuong != value))
				{
					this.OndoiTuongLuongChanging(value);
					this.SendPropertyChanging();
					this._doiTuongLuong = value;
					this.SendPropertyChanged("doiTuongLuong");
					this.OndoiTuongLuongChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_DMNguoiDuyet")]
	public partial class HT_DMNguoiDuyet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _maCongViec;
		
		private string _maPhieu;
		
		private string _maNV;
		
		private byte _trangThai;
		
		private System.Nullable<System.DateTime> _ngayDuyet;
		
		private string _lyDo;
		
		private string _noiDungDuyet;
		
		private System.Nullable<int> _trangThaiTraLai;
		
		private string _noiDung;
		
		private string _khachHang;
		
		private string _congTrinh;
		
		private string _soHopDong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnmaCongViecChanging(string value);
    partial void OnmaCongViecChanged();
    partial void OnmaPhieuChanging(string value);
    partial void OnmaPhieuChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OntrangThaiChanging(byte value);
    partial void OntrangThaiChanged();
    partial void OnngayDuyetChanging(System.Nullable<System.DateTime> value);
    partial void OnngayDuyetChanged();
    partial void OnlyDoChanging(string value);
    partial void OnlyDoChanged();
    partial void OnnoiDungDuyetChanging(string value);
    partial void OnnoiDungDuyetChanged();
    partial void OntrangThaiTraLaiChanging(System.Nullable<int> value);
    partial void OntrangThaiTraLaiChanged();
    partial void OnnoiDungChanging(string value);
    partial void OnnoiDungChanged();
    partial void OnkhachHangChanging(string value);
    partial void OnkhachHangChanged();
    partial void OncongTrinhChanging(string value);
    partial void OncongTrinhChanged();
    partial void OnsoHopDongChanging(string value);
    partial void OnsoHopDongChanged();
    #endregion
		
		public HT_DMNguoiDuyet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCongViec", DbType="VarChar(30)")]
		public string maCongViec
		{
			get
			{
				return this._maCongViec;
			}
			set
			{
				if ((this._maCongViec != value))
				{
					this.OnmaCongViecChanging(value);
					this.SendPropertyChanging();
					this._maCongViec = value;
					this.SendPropertyChanged("maCongViec");
					this.OnmaCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieu", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string maPhieu
		{
			get
			{
				return this._maPhieu;
			}
			set
			{
				if ((this._maPhieu != value))
				{
					this.OnmaPhieuChanging(value);
					this.SendPropertyChanging();
					this._maPhieu = value;
					this.SendPropertyChanged("maPhieu");
					this.OnmaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="VarChar(20)")]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="TinyInt NOT NULL")]
		public byte trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayDuyet", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayDuyet
		{
			get
			{
				return this._ngayDuyet;
			}
			set
			{
				if ((this._ngayDuyet != value))
				{
					this.OnngayDuyetChanging(value);
					this.SendPropertyChanging();
					this._ngayDuyet = value;
					this.SendPropertyChanged("ngayDuyet");
					this.OnngayDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lyDo", DbType="NVarChar(MAX)")]
		public string lyDo
		{
			get
			{
				return this._lyDo;
			}
			set
			{
				if ((this._lyDo != value))
				{
					this.OnlyDoChanging(value);
					this.SendPropertyChanging();
					this._lyDo = value;
					this.SendPropertyChanged("lyDo");
					this.OnlyDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDungDuyet", DbType="NVarChar(MAX)")]
		public string noiDungDuyet
		{
			get
			{
				return this._noiDungDuyet;
			}
			set
			{
				if ((this._noiDungDuyet != value))
				{
					this.OnnoiDungDuyetChanging(value);
					this.SendPropertyChanging();
					this._noiDungDuyet = value;
					this.SendPropertyChanged("noiDungDuyet");
					this.OnnoiDungDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThaiTraLai", DbType="Int")]
		public System.Nullable<int> trangThaiTraLai
		{
			get
			{
				return this._trangThaiTraLai;
			}
			set
			{
				if ((this._trangThaiTraLai != value))
				{
					this.OntrangThaiTraLaiChanging(value);
					this.SendPropertyChanging();
					this._trangThaiTraLai = value;
					this.SendPropertyChanged("trangThaiTraLai");
					this.OntrangThaiTraLaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDung", DbType="NVarChar(MAX)")]
		public string noiDung
		{
			get
			{
				return this._noiDung;
			}
			set
			{
				if ((this._noiDung != value))
				{
					this.OnnoiDungChanging(value);
					this.SendPropertyChanging();
					this._noiDung = value;
					this.SendPropertyChanged("noiDung");
					this.OnnoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khachHang", DbType="NVarChar(500)")]
		public string khachHang
		{
			get
			{
				return this._khachHang;
			}
			set
			{
				if ((this._khachHang != value))
				{
					this.OnkhachHangChanging(value);
					this.SendPropertyChanging();
					this._khachHang = value;
					this.SendPropertyChanged("khachHang");
					this.OnkhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_congTrinh", DbType="NVarChar(500)")]
		public string congTrinh
		{
			get
			{
				return this._congTrinh;
			}
			set
			{
				if ((this._congTrinh != value))
				{
					this.OncongTrinhChanging(value);
					this.SendPropertyChanging();
					this._congTrinh = value;
					this.SendPropertyChanged("congTrinh");
					this.OncongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soHopDong", DbType="NVarChar(500)")]
		public string soHopDong
		{
			get
			{
				return this._soHopDong;
			}
			set
			{
				if ((this._soHopDong != value))
				{
					this.OnsoHopDongChanging(value);
					this.SendPropertyChanging();
					this._soHopDong = value;
					this.SendPropertyChanged("soHopDong");
					this.OnsoHopDongChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DeNghiChiLuongChiTiet")]
	public partial class tbl_DeNghiChiLuongChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _maPhieu;
		
		private string _tenBoPhanTinhLuong;
		
		private System.Nullable<decimal> _luongThang;
		
		private System.Nullable<decimal> _phuCapCongTrinh;
		
		private System.Nullable<decimal> _phuCapKhac;
		
		private System.Nullable<decimal> _BHXH;
		
		private System.Nullable<decimal> _thueTNCN;
		
		private System.Nullable<decimal> _truyLanhTruyThu;
		
		private System.Nullable<decimal> _chuyenKhoan;
		
		private string _maCongTrinh;
		
		private string _dtLuong;
		
		private string _dtThueTN;
		
		private string _dtBHXH;
		
		private System.Nullable<decimal> _TLTTBaoHiem;
		
		private System.Nullable<decimal> _TLTTThue;
		
		private System.Nullable<decimal> _TLTTTamUng;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmaPhieuChanging(string value);
    partial void OnmaPhieuChanged();
    partial void OntenBoPhanTinhLuongChanging(string value);
    partial void OntenBoPhanTinhLuongChanged();
    partial void OnluongThangChanging(System.Nullable<decimal> value);
    partial void OnluongThangChanged();
    partial void OnphuCapCongTrinhChanging(System.Nullable<decimal> value);
    partial void OnphuCapCongTrinhChanged();
    partial void OnphuCapKhacChanging(System.Nullable<decimal> value);
    partial void OnphuCapKhacChanged();
    partial void OnBHXHChanging(System.Nullable<decimal> value);
    partial void OnBHXHChanged();
    partial void OnthueTNCNChanging(System.Nullable<decimal> value);
    partial void OnthueTNCNChanged();
    partial void OntruyLanhTruyThuChanging(System.Nullable<decimal> value);
    partial void OntruyLanhTruyThuChanged();
    partial void OnchuyenKhoanChanging(System.Nullable<decimal> value);
    partial void OnchuyenKhoanChanged();
    partial void OnmaCongTrinhChanging(string value);
    partial void OnmaCongTrinhChanged();
    partial void OndtLuongChanging(string value);
    partial void OndtLuongChanged();
    partial void OndtThueTNChanging(string value);
    partial void OndtThueTNChanged();
    partial void OndtBHXHChanging(string value);
    partial void OndtBHXHChanged();
    partial void OnTLTTBaoHiemChanging(System.Nullable<decimal> value);
    partial void OnTLTTBaoHiemChanged();
    partial void OnTLTTThueChanging(System.Nullable<decimal> value);
    partial void OnTLTTThueChanged();
    partial void OnTLTTTamUngChanging(System.Nullable<decimal> value);
    partial void OnTLTTTamUngChanged();
    #endregion
		
		public tbl_DeNghiChiLuongChiTiet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieu", DbType="VarChar(50)")]
		public string maPhieu
		{
			get
			{
				return this._maPhieu;
			}
			set
			{
				if ((this._maPhieu != value))
				{
					this.OnmaPhieuChanging(value);
					this.SendPropertyChanging();
					this._maPhieu = value;
					this.SendPropertyChanged("maPhieu");
					this.OnmaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenBoPhanTinhLuong", DbType="NVarChar(500)")]
		public string tenBoPhanTinhLuong
		{
			get
			{
				return this._tenBoPhanTinhLuong;
			}
			set
			{
				if ((this._tenBoPhanTinhLuong != value))
				{
					this.OntenBoPhanTinhLuongChanging(value);
					this.SendPropertyChanging();
					this._tenBoPhanTinhLuong = value;
					this.SendPropertyChanged("tenBoPhanTinhLuong");
					this.OntenBoPhanTinhLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luongThang", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> luongThang
		{
			get
			{
				return this._luongThang;
			}
			set
			{
				if ((this._luongThang != value))
				{
					this.OnluongThangChanging(value);
					this.SendPropertyChanging();
					this._luongThang = value;
					this.SendPropertyChanged("luongThang");
					this.OnluongThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phuCapCongTrinh", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> phuCapCongTrinh
		{
			get
			{
				return this._phuCapCongTrinh;
			}
			set
			{
				if ((this._phuCapCongTrinh != value))
				{
					this.OnphuCapCongTrinhChanging(value);
					this.SendPropertyChanging();
					this._phuCapCongTrinh = value;
					this.SendPropertyChanged("phuCapCongTrinh");
					this.OnphuCapCongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phuCapKhac", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> phuCapKhac
		{
			get
			{
				return this._phuCapKhac;
			}
			set
			{
				if ((this._phuCapKhac != value))
				{
					this.OnphuCapKhacChanging(value);
					this.SendPropertyChanging();
					this._phuCapKhac = value;
					this.SendPropertyChanged("phuCapKhac");
					this.OnphuCapKhacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHXH", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> BHXH
		{
			get
			{
				return this._BHXH;
			}
			set
			{
				if ((this._BHXH != value))
				{
					this.OnBHXHChanging(value);
					this.SendPropertyChanging();
					this._BHXH = value;
					this.SendPropertyChanged("BHXH");
					this.OnBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thueTNCN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> thueTNCN
		{
			get
			{
				return this._thueTNCN;
			}
			set
			{
				if ((this._thueTNCN != value))
				{
					this.OnthueTNCNChanging(value);
					this.SendPropertyChanging();
					this._thueTNCN = value;
					this.SendPropertyChanged("thueTNCN");
					this.OnthueTNCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_truyLanhTruyThu", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> truyLanhTruyThu
		{
			get
			{
				return this._truyLanhTruyThu;
			}
			set
			{
				if ((this._truyLanhTruyThu != value))
				{
					this.OntruyLanhTruyThuChanging(value);
					this.SendPropertyChanging();
					this._truyLanhTruyThu = value;
					this.SendPropertyChanged("truyLanhTruyThu");
					this.OntruyLanhTruyThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuyenKhoan", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> chuyenKhoan
		{
			get
			{
				return this._chuyenKhoan;
			}
			set
			{
				if ((this._chuyenKhoan != value))
				{
					this.OnchuyenKhoanChanging(value);
					this.SendPropertyChanging();
					this._chuyenKhoan = value;
					this.SendPropertyChanged("chuyenKhoan");
					this.OnchuyenKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCongTrinh", DbType="VarChar(50)")]
		public string maCongTrinh
		{
			get
			{
				return this._maCongTrinh;
			}
			set
			{
				if ((this._maCongTrinh != value))
				{
					this.OnmaCongTrinhChanging(value);
					this.SendPropertyChanging();
					this._maCongTrinh = value;
					this.SendPropertyChanged("maCongTrinh");
					this.OnmaCongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtLuong", DbType="VarChar(50)")]
		public string dtLuong
		{
			get
			{
				return this._dtLuong;
			}
			set
			{
				if ((this._dtLuong != value))
				{
					this.OndtLuongChanging(value);
					this.SendPropertyChanging();
					this._dtLuong = value;
					this.SendPropertyChanged("dtLuong");
					this.OndtLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtThueTN", DbType="VarChar(50)")]
		public string dtThueTN
		{
			get
			{
				return this._dtThueTN;
			}
			set
			{
				if ((this._dtThueTN != value))
				{
					this.OndtThueTNChanging(value);
					this.SendPropertyChanging();
					this._dtThueTN = value;
					this.SendPropertyChanged("dtThueTN");
					this.OndtThueTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtBHXH", DbType="VarChar(50)")]
		public string dtBHXH
		{
			get
			{
				return this._dtBHXH;
			}
			set
			{
				if ((this._dtBHXH != value))
				{
					this.OndtBHXHChanging(value);
					this.SendPropertyChanging();
					this._dtBHXH = value;
					this.SendPropertyChanged("dtBHXH");
					this.OndtBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TLTTBaoHiem", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TLTTBaoHiem
		{
			get
			{
				return this._TLTTBaoHiem;
			}
			set
			{
				if ((this._TLTTBaoHiem != value))
				{
					this.OnTLTTBaoHiemChanging(value);
					this.SendPropertyChanging();
					this._TLTTBaoHiem = value;
					this.SendPropertyChanged("TLTTBaoHiem");
					this.OnTLTTBaoHiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TLTTThue", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TLTTThue
		{
			get
			{
				return this._TLTTThue;
			}
			set
			{
				if ((this._TLTTThue != value))
				{
					this.OnTLTTThueChanging(value);
					this.SendPropertyChanging();
					this._TLTTThue = value;
					this.SendPropertyChanged("TLTTThue");
					this.OnTLTTThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TLTTTamUng", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TLTTTamUng
		{
			get
			{
				return this._TLTTTamUng;
			}
			set
			{
				if ((this._TLTTTamUng != value))
				{
					this.OnTLTTTamUngChanging(value);
					this.SendPropertyChanging();
					this._TLTTTamUng = value;
					this.SendPropertyChanged("TLTTTamUng");
					this.OnTLTTTamUngChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_QuiTrinhDuyetASResult
	{
		
		private int _Id;
		
		private string _TenQuiTrinh;
		
		private string _MaCongTrinh;
		
		private string _chuoiBuocDuyet;
		
		public sp_QuiTrinhDuyetASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuiTrinh", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenQuiTrinh
		{
			get
			{
				return this._TenQuiTrinh;
			}
			set
			{
				if ((this._TenQuiTrinh != value))
				{
					this._TenQuiTrinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongTrinh", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaCongTrinh
		{
			get
			{
				return this._MaCongTrinh;
			}
			set
			{
				if ((this._MaCongTrinh != value))
				{
					this._MaCongTrinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuoiBuocDuyet", DbType="NVarChar(MAX)")]
		public string chuoiBuocDuyet
		{
			get
			{
				return this._chuoiBuocDuyet;
			}
			set
			{
				if ((this._chuoiBuocDuyet != value))
				{
					this._chuoiBuocDuyet = value;
				}
			}
		}
	}
	
	public partial class sp_QuiTrinhDuyet_TrangTiepTheoResult
	{
		
		private string _MaNhanVien;
		
		private System.Nullable<int> _trangThai;
		
		public sp_QuiTrinhDuyet_TrangTiepTheoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(50)")]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this._MaNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this._trangThai = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
